project/accounts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Login
    url(r'^$', 'django.contrib.auth.views.login', 
        {'template_name' : 'accounts/home.html'}, name='home'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page' : 'accounts:home'}, name='logout'),
    url(r'^register/$', 'project.accounts.views.register', name='register'),
    url(r'^nova-senha/$', 'project.accounts.views.password_reset', name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)$', 
        'project.accounts.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^dashboard/$', 'project.accounts.views.dashboard', name='dashboard'),
    url(r'^editar/$', 'project.accounts.views.edit', name='edit'),
    url(r'^editar-senha/$', 'project.accounts.views.edit_password', name='edit_password'),
)

project/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('project.core.views',
    url(r'^', 'timer', name='timer'),
    url(r'^add-timer/(?P<status>\d+)/$', 'add_timer', name='add_timer'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('project.accounts.urls', namespace='accounts')),
    url(r'^timer/', include('project.core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

project/core/models.py
from django.db import models
from django.conf import settings

class Timer(models.Model):

	STATUS_CHOICES = (
		(0, 'Pomodoro'),
		(1, 'ShortBreak'),
		(2, 'LongBreak'),
	)

	status = models.IntegerField('Tipo', choices=STATUS_CHOICES)

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL, verbose_name='Usuário', related_name='timer'
	)

	created_at = models.DateTimeField('Criado em', auto_now_add=True)

project/core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from project.core.utils import generate_hash_key
from project.core.mail import send_mail_template

from .models import PasswordReset

User = get_user_model()

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit="True"):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['name', 'email']

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Nenhum usuário encontrado com este e-mail')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.email)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'password_reset_mail.html'
        subject = 'Criar nova senha no Pomopro'
        context = {
            'reset': reset, 
        }
        send_mail_template(subject, template_name, context, [user.email])

project/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Timer

@login_required
def timer(resquest):
    template_name = 'timer.html'
    return render(resquest, template_name)

@login_required
def add_timer(resquest, status):
	Timer(status=status, user=resquest.user).save()
	return redirect('core:timer')

project/core/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>Pomopro</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS -->
        <link rel="stylesheet" href="{% static "bower_components/materialize/dist/css/materialize.min.css" %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="{% static "css/fonts/flaticon.css" %}" rel="stylesheet">
        <link href="{% static "css/style.css" %}" rel="stylesheet">

        <!-- JS -->
        <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "bower_components/materialize/dist/js/materialize.min.js" %}"></script>

        {% block head_files %}{% endblock %}
    </head>
    <body>
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}
        {% block footer %}{% endblock %}
        {% block scripts %}{% endblock %}
    </body>
</html>

project/core/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block header %}
    <header>
        <!-- menu -->
        <nav class="white">
            <div class="nav-wrapper container">
                <a href="{% url 'core:home' %}" class="brand-logo">Pomopro</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="small material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'core:home' %}">Entrar</a></li>
                    <li><a href="{% url 'core:home' %}#sobre">Sobre</a></li>
                    <li><a href="{% url 'core:register' %}">Cadastre-se</a></li>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li><a href="{% url 'core:home' %}">Entrar</a></li>
                    <li><a href="{% url 'core:home' %}#sobre">Sobre</a></li>
                    <li><a href="{% url 'core:register' %}">Cadastre-se</a></li>
                </ul>
            </div>
        </nav>
        <!-- /menu -->
    </header>
{% endblock %}

{% block content %}
    <main>
        <!-- banner -->
        <div id="index-banner" class="parallax-container">
            <div class="section no-pad-bot">
                <div class="container">

                    <!-- titles -->
                    <br><br>
                    <h1 class="header center white-text">Pomopro</h1>
                    <div class="row center">
                        <h5 class="header col s12 white-text light">Utilize a técnica Pomodoro, e faça mais em menos tempo...</h5>
                    </div>
                    <!-- /titles -->

                    <!-- card login -->
                    <div class="row center">
                        <div class="col s12 l4 offset-l4">
                            <div class="card white z-depth-3">
                                <div class="card-content">
                                    <span class="card-title">Login</span>
                                    <form class="col s12" method="post">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}

                                        {% for field in form  %}
                                            <div class="row">
                                                <div class="input-field col s12">
                                                    {{ field }}
                                                    {{ field.label_tag }}
                                                    {{ field.errors }}
                                                </div>
                                            </div>
                                        {% endfor %}

                                        <div class="card-action">
                                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                                Entrar
                                            </button>
                                        </div>
                                    </form>
                                    <div>Não é cadastrado? <a href="{% url 'core:register' %}">Cadastre-se</a></div>
                                    <div>Esqueceu sua senha? <a href="{% url 'core:password_reset' %}">Nova senha</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /card login -->

                    <br><br>
                </div>
            </div>
            <div class="parallax"><img src="{% static "img/background1.jpg" %}" alt="Unsplashed background img 1"></div>
        </div>
        <!-- /banner -->

        <div class="container">
            <div class="section">
              <!-- icon section   -->
                <div class="row">
                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center red-text"><i class="medium material-icons">trending_up</i></h2>
                            <h5 class="center">Aumento de Produtividade</h5>

                            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center red-text"><i class="medium material-icons">track_changes</i></h2>
                            <h5 class="center">Mais Foco</h5>

                            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center red-text"><i class="medium material-icons">perm_identity</i></h2>
                            <h5 class="center">Mais tempo pra você</h5>

                            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
                        </div>
                    </div>
                </div>
                <!-- /icon section -->
            </div>
        </div>

        <!-- parallax 2 -->
        <div class="parallax-container valign-wrapper parallax-small">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row center">
                        <h5 class="header col s12 light white-text">Otimize o seu tempo agora mesmo, e trabalhe ou estude com mais foco e atenção.</h5>
                    </div>
                </div>
            </div>
            <div class="parallax"><img src="{% static "img/background2.jpg" %}" alt="Unsplashed background img 2"></div>
        </div>
        <!-- /parallax 2 -->
        
        <!-- sobre -->
        <div id="sobre" class="container">
            <div class="section">
                <div class="row">
                    <div class="col s12 center">
                        <h3><i class="medium mdi-content-send teal-text lighten-2"></i></h3>
                        <h4>Sobre a Técnica Pomodoro</h4>
                        <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
                    </div>
                </div>
                <div class="row center">
                    <div class="col s12 m2 offset-m1">
                        <span class="large-numbers">1</span>
                        <p><strong>Decida</strong> qual tarefa vai realizar</p>
                    </div>
                    <div class="col s12 m2">
                        <span class="large-numbers">2</span>
                        <p>Cronômetre <strong>25 minutos</strong>.</p>
                    </div>
                    <div class="col s12 m2">
                        <span class="large-numbers">3</span>
                        <p><strong>Trabalhe</strong> na tarefa até o alarme soar.</p>
                    </div>
                    <div class="col s12 m2">
                        <span class="large-numbers">4</span>
                        <p>Faça um pequeno <strong>intervalo</strong> de 5 minutos.</p>
                    </div>
                    <div class="col s12 m2">
                        <span class="large-numbers">5</span>
                        <p>Faça um <strong>intervalo</strong> longo de 15-30 minutos.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m8 offset-m1 border-custom center">
                        <p>Repita 4 vezes</p>                            
                    </div>
                </div>
                <div class="row">
                    <ol class="collection">
                        <li class="collection-item">
                            Liste tudo o que você precisa fazer;
                        </li>
                        <li class="collection-item">
                            Escolha uma prioridade, algo que você não deve deixar para depois;
                        </li>
                        <li class="collection-item">
                            Configure seu pomodoro através do celular (apps abaixo), do marinaratimer.com ou outro controle de tempo que escolher;
                        </li>
                        <li class="collection-item">
                            Concentre-se no estabelecido até o alarme do fim do pomodoro tocar;
                        </li>
                        <li class="collection-item">
                            Como pomodoro é uma unidade inteira (não existe meio pomodoro), mantenha uma lista para “Atividades inesperadas” ao lado da mesa em que está trabalhando. Se pensar em fazer algo não relacionado a sua tarefa atual, anote nessa folha para lembrar de fazer depois.&nbsp;Isso serve para comer, tomar água, fechar a cortina, atender ao telefone, olhar facebook ou email.
                        </li>
                        <li class="collection-item">
                            Quando o alarme tocar, faça uma pausa de 5 minutos, relaxando a mente. Só então&nbsp;comece um novo pomodoro.
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /sobre -->

        <!-- parallax 3 -->
        <div class="parallax-container valign-wrapper parallax-small">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row center">
                        <h5 class="header col s12 light white-text">Tudo pronto para você usar essa técnica da melhor forma possivel, e o melhor é free.</h5>
                    </div>
                </div>
            </div>
            <div class="parallax"><img src="{% static "img/background3.jpg" %}" alt="Unsplashed background img 2"></div>
        </div>
        <!-- /parallax 3 -->
        
        <!-- como usar -->
        <div id="cadastrar" class="container">
            <div class="section">
                <!-- title -->
                <div class="row center">
                    <h3><i class="medium material-icons red-text">settings</i></h3>
                    <h4>E agora, como usar?</h4>
                    <p>Cadastre-se e começe a usar agora mesmo, é inteiramente gratuito.</p>
                </div>
                <!-- /title -->

                <!-- button cadastre -->
                <div class="row center">
                    <a href="{% url 'core:register' %}" class="waves-effect waves-light btn-large btn-cadastrar">Cadastre-se</a>
                </div>
                <!-- button cadastre -->

            </div>
        </div>
        <!-- /como usar -->
    </main>
    
{% endblock %}

{% block footer %}
    <footer class="page-footer red">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Pomopro</h5>
            <p class="grey-text text-lighten-4">Utilize a técnica Pomodoro, e faça mais em menos tempo...</p>
          </div>
          <div class="col l2 offset-l4 s12">
            <h5 class="white-text">Social Links</h5>
            <ul class="social-links">
                <li>
                    <a class="grey-text text-lighten-3 flat-icon" href="#!">
                        <i class="flaticon-facebook29"></i>
                    </a>
                </li>
                <li>
                    <a class="grey-text text-lighten-3 flat-icon" href="#!">
                        <i class="flaticon-twitter2"></i>
                    </a>
                </li>
                <li>
                    <a class="grey-text text-lighten-3 flat-icon" href="#!">
                        <i class="flaticon-github12"></i>
                    </a>
                </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2015 Copyright - Wagner Trindade
        <a class="grey-text text-lighten-4 right" href="#!">wtrindades.com</a>
        </div>
      </div>
    </footer>

    <!-- button menu responsive -->
    <script>
        $( document ).ready(function(){
            $(".button-collapse").sideNav();
        });
    </script>
    <!-- /button menu responsive -->
    <!-- parallax -->
    <script>
        $(document).ready(function(){
            $('.parallax').parallax();
        });
    </script>
    <!-- /parallax -->

{% endblock %}

project/core/templates/password_reset.html
{% extends "home.html" %}

{% load static %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <main>
        {% if success %}
            <div id="success-form" class="container">
                <p>Email para criar uma nova senha enviado com sucesso.</p>
            </div>
            
        {% else %}
            <!-- como usar -->
            <div id="cadastrar" class="container">
                <div class="section">
                    <!-- title -->
                    <div class="row center">
                        <h3><i class="medium material-icons red-text">settings</i></h3>
                        <h4>Esqueceu sua senha?</h4>
                        <p>Recupere agora mesmo...</p>
                    </div>
                    <!-- /title -->

                    <!-- card cadastre-se -->
                        <div class="row center">
                            <div class="col s12 l4 offset-l4">
                                <div class="card white z-depth-3 pass-reset-card">
                                    <div class="card-content">
                                        <span class="card-title">Informe seu e-mail</span>
                                        <form class="col s12" method="post">
                                            {% csrf_token %}
                                            {{ form.non_field_errors }}

                                            {% for field in form %}
                                                <div class="row">
                                                    <div class="input-field col s12">
                                                        {{ field }}
                                                        {{ field.label_tag }}
                                                        {{ field.errors }}
                                                    </div>
                                                </div>
                                            {% endfor %}

                                            <div class="card-action">
                                                <button class="btn waves-effect waves-light" type="submit" name="action">
                                                    Nova senha
                                                </button>
                                            </div>
                                        </form>
                                        <div>Já é cadastrado? <a href="{% url 'core:home' %}">Fazer login</a></div>
                                        <div>Ainda não é cadastrado? <a href="{% url 'core:register' %}">Cadastre-se</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /card cadastre-se -->
                </div>
            </div>
            <!-- /como usar -->
        {% endif %}
    </main>
        
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock %}

project/core/templates/register.html
{% extends "home.html" %}

{% load static %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <main>
        <!-- como usar -->
        <div id="cadastrar" class="container">
            <div class="section">
                <!-- title -->
                <div class="row center">
                    <h3><i class="medium material-icons red-text">settings</i></h3>
                    <h4>Começe a utilizar agora mesmo...</h4>
                    <p>Inteiramente gratuito.</p>
                </div>
                <!-- /title -->

                <!-- card cadastre-se -->
                    <div class="row center">
                        <div class="col s12 l4 offset-l4">
                            <div class="card white z-depth-3">
                                <div class="card-content">
                                    <span class="card-title">Cadastre-se</span>
                                    <form class="col s12" method="post">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}

                                        {% for field in form %}
                                            <div class="row">
                                                <div class="input-field col s12">
                                                    {{ field }}
                                                    {{ field.label_tag }}
                                                    {{ field.errors }}
                                                </div>
                                            </div>
                                        {% endfor %}

                                        <div class="card-action">
                                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                                Cadastrar
                                            </button>
                                        </div>
                                    </form>
                                    <div>Já é cadastrado? <a href="{% url 'core:home' %}">Fazer login</a></div>
                                    <div>Esqueceu sua senha? <a href="{% url 'core:password_reset' %}">Nova senha</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /card cadastre-se -->
            </div>
        </div>
        <!-- /como usar -->
    </main>
        
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock %}

project/core/templates/timer.html
{% extends "base.html" %}

{% load static %}

{% block head_files %}
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{% endblock head_files %}

{% block content %}

    <div class="row">
        <!-- aside -->
        <div class="col s3 aside blue-grey darken-3">
            <!-- perfil -->
            <div class="collection">
                <div class="collection-item avatar valign-wrapper">
                    <img src="img/mussum.jpg" alt="" class="circle">
                    <span class="title valign">{{ user }}</span>
                    <a href="{% url 'accounts:dashboard' %}" class="secondary-content valign"><i class="material-icons">perm_identity</i></a>
                </div>
            </div>
            <!-- /perfil -->

            <!-- pomodoros -->
            <ul class="collapsible" data-collapsible="expandable">
                <li>
                    <div class="collapsible-header teal lighten-4">
                        <strong>Hoje</strong>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header">
                        <i class="material-icons red-text">play_circle_outline</i>
                        Pomodoro's
                    </div>
                    <div class="collapsible-body teal lighten-3">

                        {% for pomodoro in user.timer.all %}
                            {% if pomodoro.status == 0 %}
                                <span>#</span>
                            {% endif %}
                        {% endfor %}

                    </div>
                </li>
                <li>
                    <div class="collapsible-header">
                        <i class="material-icons blue-text">replay_5</i>
                        Break's
                    </div>
                    <div class="collapsible-body teal lighten-3"><p>Lorem ipsum dolor sit amet.</p></div>
                </li>
                <li>
                    <div class="collapsible-header">
                        <i class="material-icons teal-text">replay_30</i>
                        Long Break's
                    </div>
                    <div class="collapsible-body teal lighten-3"><p>Lorem ipsum dolor sit amet.</p></div>
                </li>
            </ul>
            <!-- /pomodoros -->

            <!-- sair -->
            <div class="btns-footer">
                <a href="{% url 'accounts:logout' %}" class="waves-effect waves-light btn red close">
                    <i class="material-icons left">input</i>Sair
                </a>
            </div>
            <!-- /sair -->
        </div>
        <!-- /aside -->
        
        <!-- content -->
        <div id="content" class="col s9 content offset-s3">
            <!-- title -->
            <nav class="top-nav teal">
                <div class="container">
                    <div class="nav-wrapper">
                        <a class="page-title">
                            Pomopro Timer
                        </a>
                    </div>
                </div>
            </nav>
            <!-- /title -->

            <div class="col m6 offset-m3 content-crono">
                <!-- buttons pomodoro -->
                <div class="center">
                    <a href="{% url 'core:add_timer' 0 %}" id="pomo-timer" class="waves-effect waves-light btn-large red">
                        <i class="material-icons left">play_circle_outline</i>
                        Pomodoro
                    </a>
                    <a id="short-break" class="waves-effect waves-light btn-large blue">
                        <i class="material-icons left">replay_5</i>
                        Break
                    </a>
                    <a id="long-break" class="waves-effect waves-light btn-large">
                        <i class="material-icons left">replay_30</i>
                        Long Break
                    </a>
                </div>
                <!-- buttons pomodoro -->

                <!-- number -->
                <div id="timer" class="crono-number center">
                    25:00
                </div>
                <!-- /number -->

                <!-- progress -->
                <div id="progress-bar" class="progress red lighten-4">
                    <div class="determinate red"></div>
                </div>
                <!-- /progress -->

                <!-- buttons play -->
                <div class="center">
                    <a id="play-timer" class="btn-floating btn-large waves-effect waves-light red">
                        <i class="material-icons">play_arrow</i>
                    </a>
                    <a id="pause-timer" class="btn-floating btn-large waves-effect waves-light blue">
                        <i class="material-icons">pause</i>
                    </a>
                    <a id="stop-timer" class="btn-floating btn-large waves-effect waves-light teal">
                        <i class="material-icons">stop</i>
                    </a>
                    
                </div>
                <!-- /buttons play -->

            </div>                

        </div>
        <!-- /content -->

    </div>

{% endblock content %}

{% block scripts %}
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="{% static "js/timer.js" %}" type="text/javascript"></script>
{% endblock scripts %}