project/accounts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Login
    url(r'^$', 'django.contrib.auth.views.login', 
        {'template_name' : 'accounts/home.html'}, name='home'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page' : 'accounts:home'}, name='logout'),
    url(r'^register/$', 'project.accounts.views.register', name='register'),
    url(r'^nova-senha/$', 'project.accounts.views.password_reset', name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)$', 
        'project.accounts.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^dashboard/$', 'project.accounts.views.dashboard', name='dashboard'),
    url(r'^editar/$', 'project.accounts.views.edit', name='edit'),
    url(r'^editar-senha/$', 'project.accounts.views.edit_password', name='edit_password'),
)

project/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('project.core.views',
    url(r'^', 'timer', name='timer'),
    url(r'^add-timer/(?P<status>\d+)/$', 'add_timer', name='add_timer'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('project.accounts.urls', namespace='accounts')),
    url(r'^timer/', include('project.core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.conf import settings


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User Custom with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User
    """

    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100)
    date_birth = models.DateField('Data de Nascimento', null=True, blank=True)
    image = models.ImageField(
        upload_to="core/images", verbose_name='Imagem', null=True, blank=True
    )
    is_staff = models.BooleanField('É administrador?', blank=True, default=False)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.name

    def get_short_name(self):
        return str(self)

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name='Usuário'
        verbose_name_plural='Usuários'

class PasswordReset(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', related_name='resets')
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return "{0} em {1}".format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

project/accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from project.core.utils import generate_hash_key
from project.core.mail import send_mail_template

from .models import PasswordReset

User = get_user_model()

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit="True"):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['name', 'email']

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Nenhum usuário encontrado com este e-mail')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.email)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha no Pomopro'
        context = {
            'reset': reset, 
        }
        send_mail_template(subject, template_name, context, [user.email])

class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['image', 'name', 'email', 'date_birth']

project/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import SetPasswordForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import RegisterForm, PasswordResetForm, EditAccountForm
from .models import PasswordReset 

@login_required
def dashboard(resquest):
    template_name = 'accounts/dashboard.html'
    context = {}
    return render(resquest, template_name, context)

def register(resquest):
    template_name = 'accounts/register.html'
    if resquest.method == 'POST':
        form = RegisterForm(resquest.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                email=user.email, password= form.cleaned_data['password1']
            )
            login(resquest, user)
            return redirect('core:timer')
    else:
        form = RegisterForm()
    context = {
        'form' : form
    }
    return render(resquest, template_name, context)

def password_reset(resquest):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(resquest.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(resquest, template_name, context)

def password_reset_confirm(resquest, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=resquest.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(resquest, template_name, context)

@login_required
def edit(resquest):
    template_name = 'accounts/edit.html'
    context = {}
    if resquest.method == 'POST':
        form = EditAccountForm(resquest.POST, instance=resquest.user)
        if form.is_valid():
            form.save()
            messages.success(resquest, 'Os dados de sua conta foram alterados com sucesso.')
            return redirect('accounts:dashboard')
    else:
        form = EditAccountForm(instance=resquest.user)
    context['form'] = form 
    return render(resquest, template_name, context)

@login_required
def edit_password(resquest):
    template_name = 'accounts/edit_password.html'
    context = {}
    if resquest.method == 'POST':
        form = PasswordChangeForm(data=resquest.POST, user=resquest.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=resquest.user)
    context['form'] = form
    return render(resquest, template_name, context)

project/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block head_files %}
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{% endblock head_files %}

{% block content %}
    <main>

        <div class="row">
            <!-- aside -->
            <div class="col s3 aside blue-grey darken-3">
                <!-- perfil -->
                <div class="collection">
                    <div class="collection-item avatar valign-wrapper">
                        <img src="img/mussum.jpg" alt="" class="circle">
                        <span class="title valign">{{ user }}</span>
                        <a href="{% url 'accounts:dashboard' %}" class="secondary-content valign"><i class="material-icons">perm_identity</i></a>
                    </div>
                </div>
                <!-- /perfil -->
                
                <!-- menu editar -->
                <div class="collection">
                    <a href="#!" class="collection-item active">Meu perfil</a>
                    <a href="{% url 'accounts:edit' %}" class="collection-item">Editar perfil</a>
                    <a href="{% url 'accounts:edit_password' %}" class="collection-item">Editar senha</a>
                </div>
                <!-- /menu editar -->

                
                <div class="btns-footer">
                    <!-- sair -->
                    <a href="{% url 'accounts:logout' %}" class="waves-effect waves-light btn red btn-close">
                        <i class="material-icons left">input</i>
                        Sair
                    </a>
                    <!-- /sair -->
                    
                    <!-- timer -->
                    <a href="{% url 'core:timer' %}" class="waves-effect waves-light btn blue btn-pomopro">
                        <i class="material-icons left">query_builder</i>
                        Pomopro Timer
                    </a>
                    <!-- /timer -->                        
                </div>
                


            </div>
            <!-- /aside -->
            
            <!-- content -->
            <div id="content" class="col s9 content offset-s3">
                <!-- title -->
                <nav class="top-nav teal">
                    <div class="container">
                        <div class="nav-wrapper">
                            <a class="page-title">
                                Meu Perfil
                            </a>
                        </div>
                    </div>
                </nav>
                <!-- /title -->

                <div class="container content-perfil">
                    <div class="row message">
                        {% for message in messages  %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                    <img src="img/mussum.jpg" alt="" class="circle">
                    <ul>
                        <li><strong>Nome</strong>: {{ user }}</li>
                        <li><strong>E-mail</strong>: {{ user.email }}</li>
                        <li><strong>Data Nascimento</strong>: {{ user.date_birth|date:'d/m/Y' }}</li>
                    </ul>
                </div>
            </div>
            <!-- /content -->

        </div>

    </main>
{% endblock %}

project/accounts/templates/accounts/edit.html
{% extends "base.html" %}

{% load static %}

{% block head_files %}
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{% endblock head_files %}

{% block content %}
    <main>

        <div class="row">
            <!-- aside -->
            <div class="col s3 aside blue-grey darken-3">
                <!-- perfil -->
                <div class="collection">
                    <div class="collection-item avatar valign-wrapper">
                        <img src="img/mussum.jpg" alt="" class="circle">
                        <span class="title valign">{{ user }}</span>
                        <a href="{% url 'accounts:dashboard' %}" class="secondary-content valign"><i class="material-icons">perm_identity</i></a>
                    </div>
                </div>
                <!-- /perfil -->
                
                <!-- menu editar -->
                <div class="collection">
                    <a href="{% url 'accounts:dashboard' %}" class="collection-item">Meu perfil</a>
                    <a href="{% url 'accounts:edit' %}" class="collection-item active">Editar perfil</a>
                    <a href="#!" class="collection-item">Editar senha</a>
                </div>
                <!-- /menu editar -->

                
                <div class="btns-footer">
                    <!-- sair -->
                    <a href="{% url 'accounts:logout' %}" class="waves-effect waves-light btn red btn-close">
                        <i class="material-icons left">input</i>
                        Sair
                    </a>
                    <!-- /sair -->
                    
                    <!-- timer -->
                    <a href="{% url 'core:timer' %}" class="waves-effect waves-light btn blue btn-pomopro">
                        <i class="material-icons left">query_builder</i>
                        Pomopro Timer
                    </a>
                    <!-- /timer -->                        
                </div>
                


            </div>
            <!-- /aside -->
            
            <!-- content -->
            <div id="content" class="col s9 content offset-s3">
                <!-- title -->
                <nav class="top-nav teal">
                    <div class="container">
                        <div class="nav-wrapper">
                            <a class="page-title">
                                Editar Perfil
                            </a>
                        </div>
                    </div>
                </nav>
                <!-- /title -->

                <div class="container content-perfil">
                    <form class="col s12 m6" method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}

                        {% for field in form %}
                            <div class="row">
                                <div class="input-field col s12">
                                    {{ field }}
                                    {{ field.label_tag }}
                                    {{ field.errors }}
                                </div>
                            </div>
                        {% endfor %}

                        <div class="card-action">
                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                Alterar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /content -->

        </div>

    </main>
{% endblock %}

project/accounts/templates/accounts/edit_password.html
{% extends "base.html" %}

{% load static %}

{% block head_files %}
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{% endblock head_files %}

{% block content %}
    <main>

        <div class="row">
            <!-- aside -->
            <div class="col s3 aside blue-grey darken-3">
                <!-- perfil -->
                <div class="collection">
                    <div class="collection-item avatar valign-wrapper">
                        <img src="" alt="" class="circle">
                        <span class="title valign">{{ user }}</span>
                        <a href="{% url 'accounts:dashboard' %}" class="secondary-content valign"><i class="material-icons">perm_identity</i></a>
                    </div>
                </div>
                <!-- /perfil -->
                
                <!-- menu editar -->
                <div class="collection">
                    <a href="{% url 'accounts:dashboard' %}" class="collection-item">Meu perfil</a>
                    <a href="{% url 'accounts:edit' %}" class="collection-item">Editar perfil</a>
                    <a href="#!" class="collection-item active">Editar senha</a>
                </div>
                <!-- /menu editar -->

                
                <div class="btns-footer">
                    <!-- sair -->
                    <a href="{% url 'accounts:logout' %}" class="waves-effect waves-light btn red btn-close">
                        <i class="material-icons left">input</i>
                        Sair
                    </a>
                    <!-- /sair -->
                    
                    <!-- timer -->
                    <a href="{% url 'core:timer' %}" class="waves-effect waves-light btn blue btn-pomopro">
                        <i class="material-icons left">query_builder</i>
                        Pomopro Timer
                    </a>
                    <!-- /timer -->                        
                </div>
                


            </div>
            <!-- /aside -->
            
            <!-- content -->
            <div id="content" class="col s9 content offset-s3">
                <!-- title -->
                <nav class="top-nav teal">
                    <div class="container">
                        <div class="nav-wrapper">
                            <a class="page-title">
                                Editar Senha
                            </a>
                        </div>
                    </div>
                </nav>
                <!-- /title -->

                <div class="container content-perfil">
                    {% if success %}
                        <div class="row message">
                            <p>Sua senha foi alterada com sucesso.</p>
                        </div>
                    {% endif %}
                    <form class="col s12 m6" method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}

                        {% for field in form %}
                            <div class="row">
                                <div class="input-field col s12">
                                    {{ field }}
                                    {{ field.label_tag }}
                                    {{ field.errors }}
                                </div>
                            </div>
                        {% endfor %}

                        <div class="card-action">
                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                Alterar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /content -->

        </div>

    </main>
{% endblock %}

project/accounts/templates/accounts/password_reset.html
{% extends "accounts/home.html" %}

{% load static %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <main>
        {% if success %}
            <div id="success-form" class="container">
                <p>Email para criar uma nova senha enviado com sucesso.</p>
            </div>
        {% else %}
            <!-- como usar -->
            <div id="cadastrar" class="container">
                <div class="section">
                    <!-- title -->
                    <div class="row center">
                        <h3><i class="medium material-icons red-text">settings</i></h3>
                        <h4>Esqueceu sua senha?</h4>
                        <p>Recupere agora mesmo...</p>
                    </div>
                    <!-- /title -->

                    <!-- card cadastre-se -->
                    <div class="row center">
                        <div class="col s12 l4 offset-l4">
                            <div class="card white z-depth-3 pass-reset-card">
                                <div class="card-content">
                                    <span class="card-title">Informe seu e-mail</span>
                                    <form class="col s12" method="post">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}

                                        {% for field in form %}
                                            <div class="row">
                                                <div class="input-field col s12">
                                                    {{ field }}
                                                    {{ field.label_tag }}
                                                    {{ field.errors }}
                                                </div>
                                            </div>
                                        {% endfor %}

                                        <div class="card-action">
                                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                                Nova senha
                                            </button>
                                        </div>
                                    </form>
                                    <div>Já é cadastrado? <a href="{% url 'accounts:home' %}">Fazer login</a></div>
                                    <div>Ainda não é cadastrado? <a href="{% url 'accounts:register' %}">Cadastre-se</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /card cadastre-se -->
                </div>
            </div>
            <!-- /como usar -->
        {% endif %}
    </main>
        
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock %}

project/accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/home.html" %}

{% load static %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <main>
        {% if success %}
            <div id="success-form" class="container">
                <p>Sua senha foi criada com sucesso.</p>
            </div>
        {% else %}
            <!-- como usar -->
            <div id="cadastrar" class="container">
                <div class="section">
                    <!-- title -->
                    <div class="row center">
                        <h3><i class="medium material-icons red-text">settings</i></h3>
                        <h4>Crie sua nova senha</h4>
                    </div>
                    <!-- /title -->

                    <!-- card cadastre-se -->
                        <div class="row center">
                            <div class="col s12 l4 offset-l4">
                                <div class="card white z-depth-3 pass-reset-card">
                                    <div class="card-content">
                                        <span class="card-title">Informe sua nova senha</span>
                                        <form class="col s12" method="post">
                                            {% csrf_token %}
                                            {{ form.non_field_errors }}

                                            {% for field in form %}
                                                <div class="row">
                                                    <div class="input-field col s12">
                                                        {{ field }}
                                                        {{ field.label_tag }}
                                                        {{ field.errors }}
                                                    </div>
                                                </div>
                                            {% endfor %}

                                            <div class="card-action">
                                                <button class="btn waves-effect waves-light" type="submit" name="action">
                                                    Enviar
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /card cadastre-se -->
                </div>
            </div>
            <!-- /como usar -->
        {% endif %}
    </main>
        
{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock %}

project/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link: <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para criar nova senha">Criar Nova Senha</a></p>

project/accounts/templates/accounts/register.html
{% extends "accounts/home.html" %}

{% load static %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <main>
        <!-- como usar -->
        <div id="cadastrar" class="container">
            <div class="section">
                <!-- title -->
                <div class="row center">
                    <h3><i class="medium material-icons red-text">settings</i></h3>
                    <h4>Começe a utilizar agora mesmo...</h4>
                    <p>Inteiramente gratuito.</p>
                </div>
                <!-- /title -->

                <!-- card cadastre-se -->
                    <div class="row center">
                        <div class="col s12 l4 offset-l4">
                            <div class="card white z-depth-3">
                                <div class="card-content">
                                    <span class="card-title">Cadastre-se</span>
                                    <form class="col s12" method="post">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}

                                        {% for field in form %}
                                            <div class="row">
                                                <div class="input-field col s12">
                                                    {{ field }}
                                                    {{ field.label_tag }}
                                                    {{ field.errors }}
                                                </div>
                                            </div>
                                        {% endfor %}

                                        <div class="card-action">
                                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                                Cadastrar
                                            </button>
                                        </div>
                                    </form>
                                    <div>Já é cadastrado? <a href="{% url 'accounts:home' %}">Fazer login</a></div>
                                    <div>Esqueceu sua senha? <a href="{% url 'accounts:password_reset' %}">Nova senha</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /card cadastre-se -->
            </div>
        </div>
        <!-- /como usar -->
    </main>
        
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock %}